version: '3.9'
services:
  sentiment:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"
    container_name: fastapi
    networks:
      docker_network:
        ipv4_address: 172.27.1.1
  authentication:
    image: authentication_image:latest
    container_name: authentication_test
    volumes:
      - ./my_volume:/shared_volume
    networks:
      docker_network:
        ipv4_address: 172.27.1.2
    environment: 
      LOG: "1"
    depends_on:
      - "sentiment"
  authorization:
    image: authorization_image:latest
    container_name: authorization_test
    volumes:
      - ./my_volume:/shared_volume
    networks:
      docker_network:
        ipv4_address: 172.27.1.3
    environment:
      LOG: "1"
    depends_on:
      - "sentiment"
  content:
    image: content_image:latest
    container_name: content_test
    volumes:
      - ./my_volume:/shared_volume
    networks:
      docker_network:
        ipv4_address: 172.27.1.4
    environment:
       LOG: "1"
    depends_on:
      - "sentiment"
networks:
  docker_network:
      ipam:
         driver: default
         config:
            - subnet: 172.27.0.0/16
